"""Cultural heritage tourism value: tourism receipts attributable to cultural assets.

International tourism receipts (ST.INT.RCPT.CD) proxy the economic value
generated by cultural and heritage sites. Countries with dense UNESCO World
Heritage Site listings tend to capture higher cultural tourism premiums. Per-
capita receipts reveal the depth of tourism monetization.

Score: very low receipts -> STABLE undeveloped cultural tourism sector,
moderate -> WATCH emerging, high -> STRESS significant but potentially fragile
dependence, very high -> CRISIS over-tourism risk with cultural erosion.
"""

from __future__ import annotations

from app.layers.base import LayerBase


class CulturalHeritageTourismValue(LayerBase):
    layer_id = "lAR"
    name = "Cultural Heritage Tourism Value"
    weight = 0.20

    async def compute(self, db, **kwargs) -> dict:
        rcpt_code = "ST.INT.RCPT.CD"
        pop_code = "SP.POP.TOTL"

        rcpt_rows = await db.fetch_all(
            "SELECT value FROM data_points WHERE series_id = "
            "(SELECT id FROM data_series WHERE indicator_code = ? OR name LIKE ?) "
            "ORDER BY date DESC LIMIT 15",
            (rcpt_code, "%tourism receipts%"),
        )
        pop_rows = await db.fetch_all(
            "SELECT value FROM data_points WHERE series_id = "
            "(SELECT id FROM data_series WHERE indicator_code = ? OR name LIKE ?) "
            "ORDER BY date DESC LIMIT 15",
            (pop_code, "%Population, total%"),
        )

        rcpt_vals = [r["value"] for r in rcpt_rows if r["value"] is not None]
        pop_vals = [r["value"] for r in pop_rows if r["value"] is not None]

        if not rcpt_vals:
            return {
                "score": None,
                "signal": "UNAVAILABLE",
                "error": "no data for ST.INT.RCPT.CD",
            }

        rcpt_latest = rcpt_vals[0]
        trend = round(rcpt_vals[0] - rcpt_vals[-1], 2) if len(rcpt_vals) > 1 else None

        # Per-capita receipts in USD if population available
        per_capita = None
        if pop_vals and pop_vals[0] > 0:
            per_capita = rcpt_latest / pop_vals[0]

        # Score on per-capita receipts (USD): <10 = STABLE, 10-100 = WATCH, 100-500 = STRESS, >500 = CRISIS
        if per_capita is not None:
            ref = per_capita
            if ref < 10.0:
                score = 5.0 + ref * 1.5
            elif ref < 100.0:
                score = 20.0 + (ref - 10.0) * 0.33
            elif ref < 500.0:
                score = 49.7 + (ref - 100.0) * 0.063
            else:
                score = min(100.0, 74.9 + (ref - 500.0) * 0.025)
        else:
            # Fallback: raw receipts in billions USD
            billions = rcpt_latest / 1e9
            if billions < 1.0:
                score = 10.0 + billions * 10.0
            elif billions < 10.0:
                score = 20.0 + (billions - 1.0) * 3.33
            elif billions < 50.0:
                score = 49.97 + (billions - 10.0) * 0.625
            else:
                score = min(100.0, 74.97 + (billions - 50.0) * 0.25)

        return {
            "score": round(score, 2),
            "signal": self.classify_signal(score),
            "metrics": {
                "tourism_receipts_usd": round(rcpt_latest, 2),
                "per_capita_receipts_usd": round(per_capita, 4) if per_capita is not None else None,
                "trend_receipts_usd": trend,
                "n_obs_receipts": len(rcpt_vals),
                "n_obs_pop": len(pop_vals),
            },
        }
